Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.ssh.private_key_path = ["/home/vagrant/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
	$websrv1 = 2
	$websrv2 = 0
	$lbsrv = 1
	$dbsrv = 1
	(1..$websrv1).each do |i|
		config.vm.define "klant1-productie-web0#{i}" do |web1|
		web1.vm.box = "ubuntu/xenial64"
		web1.vm.hostname = "klant1-productie-web0#{i}"
		web1.vm.network "private_network", ip: "192.168.20.1#{i}"
		web1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		web1.vm.provider "virtualbox" do |vbweb1|
			vbweb1.memory = "512"
			vbweb1.gui = false
			vbweb1.name = "klant1-productie-web0#{i}"
			end
		end
	end
	(1..$websrv2).each do |q|
		config.vm.define "klant1-productie-web0#{q}" do |web2|
		web2.vm.box = "ubuntu/xenial64"
		web2.vm.hostname = "klant1-productie-web0#{q}"
		web2.vm.network "private_network", ip: "192.168.20.2#{q}"
		web2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		web2.vm.provider "virtualbox" do |vbweb2|
			vbweb2.memory = "512"
			vbweb2.gui = false
			vbweb2.name = "klant1-productie-web0#{q}"
			end
		end
	end
	(1..$lbsrv).each do |y|
		config.vm.define "klant1-productie-lb0#{y}" do |lb|
		lb.vm.box = "ubuntu/xenial64"
		lb.vm.hostname = "klant1-productie-lb0#{y}"
		lb.vm.network "private_network", ip: "192.168.20.3#{y}"
		lb.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		lb.vm.provider "virtualbox" do |vblb|
			vblb.memory = "512"
			vblb.gui = false
			vblb.name = "klant1-productie-lb0#{y}"
			end
		end
	end
	(1..$dbsrv).each do |x|
		config.vm.define "klant1-productie-db0#{x}" do |db|
		db.vm.box = "ubuntu/xenial64"
		db.vm.hostname = "klant1-productie-db0#{x}"
		db.vm.network "private_network", ip: "192.168.20.4#{x}"
		db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		db.vm.provider "virtualbox" do |vbdb|
			vbdb.memory = "512"
			vbdb.gui = false
			vbdb.name = "klant1-productie-db0#{x}"
			end
		end
	end
end
