Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.ssh.private_key_path = ["/home/vagrant/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
	$instances = 2
	(1..$instances).each do |i|
		#$ip = "192.168.20.#{i+1}"
		config.vm.define "klant1-productie-web0#{i}" do |node|
		node.vm.box = "ubuntu/xenial64"
		node.vm.hostname = "klant1-productie-web0#{i}"
		node.vm.network "private_network", ip: "192.168.20.2#{i}"
		node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		node.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
			vb.gui = false
			vb.name = "klant1-productie-web0#{i}"
			end
		end
	end
end