Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.ssh.private_key_path = ["/home/vagrant/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
	$websrv = 2
	$lbsrv = 1
	$dbsrv = 1
	(1..$websrv).each do |i|
		config.vm.define "klant1-productie-web0#{i}" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.hostname = "klant1-productie-web0#{i}"
		web.vm.network "private_network", ip: "192.168.20.2#{i}"
		web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		web.vm.provider "virtualbox" do |vbweb|
			vbweb.memory = "512"
			vbweb.gui = false
			vbweb.name = "klant1-productie-web0#{i}"
			end
		end
	end
	(1..$lbsrv).each do |y|
		config.vm.define "klant1-productie-lb0#{y}" do |lb|
		lb.vm.box = "ubuntu/xenial64"
		lb.vm.hostname = "klant1-productie-lb0#{y}"
		lb.vm.network "private_network", ip: "192.168.20.3#{y}"
		lb.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		lb.vm.provider "virtualbox" do |vblb|
			vblb.memory = "512"
			vblb.gui = false
			vblb.name = "klant1-productie-lb0#{y}"
			end
		end
	end
	(1..$dbsrv).each do |x|
		config.vm.define "klant1-productie-db0#{x}" do |db|
		db.vm.box = "ubuntu/xenial64"
		db.vm.hostname = "klant1-productie-db0#{x}"
		db.vm.network "private_network", ip: "192.168.20.4#{x}"
		db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		db.vm.provider "virtualbox" do |vbdb|
			vbdb.memory = "512"
			vbdb.gui = false
			vbdb.name = "klant1-productie-db0#{x}"
			end
		end
	end
end
