- hosts: loadbalancer
  become: true
  gather_facts: yes

  vars:
    haproxy_app_name: haproxy
    haproxy_mode: http
    haproxy_enable_stats: enable 
    haproxy_algorithm: roundrobin
    haproxy_backend_servers:
      - {name: klant1-productie-web01, ip: 192.168.20.21, port: 80, paramstring: cookie A check}
      - {name: klant1-productie-web02, ip: 192.168.20.22, port: 80, paramstring: cookie B check}
    haproxy_stats_users:
      - {username: vagrant, password: vagrant}
  
  tasks:
    - name: Update apt cache 
      apt: update_cache=yes cache_valid_time=3600      

    - name: Install haproxy
      apt: name=haproxy state=present

    - name: Enable init script
      lineinfile:
        path: /etc/default/haproxy
        regexp: '^ENABLED='
        line: ENABLED=1

    - name: Update HAProxy config
      template: src=~/HDD/VM2/playbooks/templates/haproxy.cfg 
            dest=/etc/haproxy/haproxy.cfg 

      notify: 
        - restart haproxy

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted