Vagrant.configure("2") do |config|

	config.ssh.insert_key = false
	config.ssh.private_key_path = ["/home/vagrant/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
	$websrv1 = 1
	$websrv2 = 1
	$lbsrv = 1
	$dbsrv = 1
	(1..$websrv1).each do |i|
		config.vm.define "coen-test-wbsrv01" do |web1|
		web1.vm.box = "ubuntu/xenial64"
		web1.vm.hostname = "coen-test-wbsrv01"
		web1.vm.network "private_network", ip: "192.168.20.5#{i}"
		web1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		web1.vm.provider "virtualbox" do |vbweb1|
			vbweb1.memory = "1536"
			vbweb1.gui = false
			vbweb1.name = "coen-test-wbsrv01"
			end
		end
	end
	(1..$websrv2).each do |q|
		config.vm.define "coen-test-wbsrv02" do |web2|
		web2.vm.box = "ubuntu/xenial64"
		web2.vm.hostname = "coen-test-wbsrv02"
		web2.vm.network "private_network", ip: "192.168.20.6#{q}"
		web2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		web2.vm.provider "virtualbox" do |vbweb2|
			vbweb2.memory = "1536"
			vbweb2.gui = false
			vbweb2.name = "coen-test-wbsrv02"
			end
		end
	end
	(1..$lbsrv).each do |y|
		config.vm.define "coen-test-lbsrv01" do |lb|
		lb.vm.box = "ubuntu/xenial64"
		lb.vm.hostname = "coen-test-lbsrv01"
		lb.vm.network "private_network", ip: "192.168.20.7#{y}"
		lb.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		lb.vm.provider "virtualbox" do |vblb|
			vblb.memory = "1536"
			vblb.gui = false
			vblb.name = "coen-test-lbsrv01"
			end
		end
	end
	(1..$dbsrv).each do |x|
		config.vm.define "coen-test-dbsrv01" do |db|
		db.vm.box = "ubuntu/xenial64"
		db.vm.hostname = "coen-test-dbsrv01"
		db.vm.network "private_network", ip: "192.168.20.8#{x}"
		db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		db.vm.provider "virtualbox" do |vbdb|
			vbdb.memory = "1536"
			vbdb.gui = false
			vbdb.name = "coen-test-dbsrv01"
			end
		end
	end
end
