---
- name: Apply common applications
  hosts: all
  become: true

  roles:
    - common

- name: Apply webserver configuration
  hosts: [webservers]
  become: true

  roles:
    - webserver

- name: Apply loadbalancer configuration
  hosts: [loadbalancer]
  become: true

  roles:
    - loadbalancer