---
- name: Apply webserver configuration
  hosts: [webservers]
  become: true

  roles:
    - webserver

- name: Apply Loadbalancer configuration
  hosts: [loadbalancer]
  become: true

  roles:
    - loadbalancer

- name: Apply database configuration
  hosts: [database]
  become: true


  roles:
    - database
