---
- name: Apply webserver configuration
  hosts: [webservers]
  become: true

  roles:
    - webserver

#- name: Apply database configuration
#  hosts: [database]
#  become: true


#  roles:
#    - database
