- name: Update apt cache 
  apt: update_cache=yes cache_valid_time=3600

- name: Install haproxy
  apt: name=haproxy state=present

- name: Enable init script
  lineinfile:
    path: /etc/default/haproxy
    regexp: '^ENABLED='
    line: ENABLED=1

- name: Update HAProxy config
  template: src=~/HDD/VM2/playbooks/roles/loadbalancer/files/haproxy.cfg
            dest=/etc/haproxy/haproxy.cfg 

  notify: 
  - restart haproxy